### ISSUE TITLE
[compile] error  include/nop/base/logical_buffer.h:135:14: error: uninitialized variable ‘size’ in ‘constexpr’ function

### ISSUE THREAD

**Issue by feng-y** [google/libnop#15]
In file included from include/nop/traits/is_fungible.h:28:0,
                 from include/nop/protocol.h:21,
                 from examples/shared.cpp:24:
include/nop/base/logical_buffer.h: In instantiation of ‘static constexpr nop::Status<void> nop::Encoding<nop::LogicalBuffer<BufferType, SizeType, IsUnbounded>, typename std::enable_if<(! nop::IsIntegral<typename nop::ArrayTraits<T>::ElementType>::value), void>::type>::ReadPayload(nop::EncodingByte, nop::Encoding<nop::LogicalBuffer<BufferType, SizeType, IsUnbounded>, typename std::enable_if<(! nop::IsIntegral<typename nop::ArrayTraits<T>::ElementType>::value), void>::type>::Type*, Reader*) [with Reader = nop::BufferReader; BufferType = {anonymous}::Triangle [1]; SizeType = long unsigned int; bool IsUnbounded = true; nop::Encoding<nop::LogicalBuffer<BufferType, SizeType, IsUnbounded>, typename std::enable_if<(! nop::IsIntegral<typename nop::ArrayTraits<T>::ElementType>::value), void>::type>::Type = nop::LogicalBuffer<{anonymous}::Triangle [1], long unsigned int, true, void>]’:
include/nop/types/detail/member_pointer.h:146:39:   required from ‘static constexpr nop::Status<void> nop::MemberPointer<First Class::*, FirstPointer, Second Class::*, SecondPointer, typename std::enable_if<nop::IsLogicalBufferPair<First, Second>::value, void>::type>::ReadPayload(nop::EncodingByte, Class*, Reader*, MemberList) [with Reader = nop::BufferReader; MemberList = nop::MemberList<nop::MemberPointer<{anonymous}::Triangle ({anonymous}::CPolyhedron::*)[1], &{anonymous}::CPolyhedron::triangles, long unsigned int {anonymous}::CPolyhedron::*, &{anonymous}::CPolyhedron::size, void> >; Class = {anonymous}::CPolyhedron; First = {anonymous}::Triangle [1]; Second = long unsigned int; First Class::* FirstPointer = &{anonymous}::CPolyhedron::triangles; Second Class::* SecondPointer = &{anonymous}::CPolyhedron::size]’
include/nop/base/value.h:64:32:   required from ‘static constexpr nop::Status<void> nop::Encoding<T, typename std::enable_if<nop::IsValueWrapper<T>::value, void>::type>::ReadPayload(nop::EncodingByte, T*, Reader*) [with Reader = nop::BufferReader; T = {anonymous}::CPolyhedron]’
include/nop/base/encoding.h:132:38:   required from ‘static constexpr nop::Status<void> nop::EncodingIO<T>::Read(T*, Reader*) [with Reader = nop::BufferReader; T = {anonymous}::CPolyhedron]’
include/nop/base/serializer.h:178:29:   required from ‘constexpr nop::Status<void> nop::Deserializer<Reader>::Read(T*) [with T = {anonymous}::CPolyhedron; Reader = nop::BufferReader]’
include/nop/protocol.h:40:36:   required from ‘static constexpr nop::Status<void> nop::Protocol<ProtocolType>::Read(Deserializer*, T*) [with Deserializer = nop::Deserializer<nop::BufferReader>; T = {anonymous}::CPolyhedron; Enable = void; ProtocolType = {anonymous}::Polyhedron]’
examples/shared.cpp:119:68:   required from here
include/nop/base/logical_buffer.h:135:14: error: uninitialized variable ‘size’ in ‘constexpr’ function
     SizeType size;

g++: 6.4.0
os:3.10.0-693.el7.x86_64

**Comment by eieio** [comment]
Fixed in master. Thanks!
