### ISSUE TITLE
example did not work.

### ISSUE THREAD

**Issue by dotkt** [google/libnop#22]
![图片](https://user-images.githubusercontent.com/49758966/100889443-155bcd80-34f2-11eb-8abc-de74af295e93.png)

i use the sample code in readme but the result is strange .is something wrong?

win10 vs2019

**Comment by eieio** [comment]
Hello,

This library is not tested on any of the Visual Studio compilers. Judging by the output, it looks like the macro magic in `NOP_STRUCTURE` fails to expand correctly and the resulting type describing the members of `Person` has zero entries.

Unfortunately, I don't have a Windows machine handy. It will be difficult for me to track down the issue for you.

**Comment by dotkt** [comment]
yes you are right. i dump the compile temp file and see the macro did not work.
i 'll try to fix it. the macro is very complex to me,it will need some time.
