### ISSUE TITLE
Vector serialization crashing on MSVC 19.20.27508.1 for x64

### ISSUE THREAD

**Issue by arthurpassos** [google/libnop#4]
Whenever I try to serialize a vector, it crashes reporting a vector subscript out of range.

Here's a screenshot of the crash report and the code that caused it:

![image](https://user-images.githubusercontent.com/31894389/61906497-d97a2680-af01-11e9-9c67-d84f08472844.png)

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Assertion Failed!

Program: ...CLionProjects\test_newint4\cmake-build-debug\test_newint4.exe
File: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\vector
Line: 1371

Expression: vector subscript out of range

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------

```
//
// Created by PC on 7/25/2019.
//

#include "catch.hpp"
#include <nop/serializer.h>
#include <nop/utility/buffer_reader.h>
#include <nop/utility/buffer_writer.h>
#include "Geographics/GeoPoint.h"

SCENARIO("check serializer and deserializer", "[de-serializer]")
{
    GIVEN("A Serializer and a Deserializer with a 30 byte buffer")
    {
        constexpr std::size_t kBufferSize = 1048;
        std::uint8_t buffer[kBufferSize];
        nop::Serializer<nop::BufferWriter> serializer{buffer, kBufferSize};
        nop::Deserializer<nop::BufferReader> deserializer{buffer, kBufferSize};

        WHEN("Arthur at ravex, 25/07/2019 in areas 15, 658, 743 and 25")
        {
            GeoPoint in_position {-27.5872, -48.2968};
            Person in_person {"Arthur", 21};
            std::vector<uint32_t> in_areas {15, 658, 743, 25};
            uint32_t in_timestamp = 1564057349;

            serializer.Write(in_position);
            serializer.Write(in_areas);
            serializer.Write(in_person);
            serializer.Write(in_timestamp);

            THEN("Out should be the same as input")
            {
                GeoPoint out_position;
                Person out_person;
                std::vector<uint32_t> out_areas;
                uint32_t out_timestamp;

                deserializer.Read(&out_position);
                deserializer.Read(&out_person);
                deserializer.Read(&out_areas);
                deserializer.Read(&out_timestamp);



                REQUIRE(in_position == out_position);
                REQUIRE(in_person == out_person);
                REQUIRE(in_areas == out_areas);
                REQUIRE(in_timestamp == out_timestamp);
            }
        }
    }
}
```

I'm running on Windows and building with MSVC 19.20.27508.1 for x64 . Please note that it works perfectly on GCC.

**Comment by eieio** [comment]
Thanks for your patience getting back to you.

While libnop doesn't explicitly support MSVC, I think this issue should be fixable.

It seems that MSVC does bounds checking on `operator[]` in debug builds, even though the standard specifies that bounds checking is not performed. Computing an address one past the end of an array is standards compliant, so MSVC is technically incorrect here.

That being said, we can work around this with a simple change to: [https://github.com/google/libnop/blob/master/include/nop/base/vector.h#L146](https://github.com/google/libnop/blob/master/include/nop/base/vector.h#L146)

Replacing that line with this should do the trick:

`return writer->Write(value.data(), value.data() + length);`

A similar change is necessary here: [https://github.com/google/libnop/blob/master/include/nop/base/vector.h#L169](https://github.com/google/libnop/blob/master/include/nop/base/vector.h#L169)

`return reader->Read(value->data(), value->data() + length);`

If you would like to verify these changes in your local environment, I'm happy to take a pull request.

**Comment by eieio** [comment]
Fixed on master.

Cheers
